// <auto-generated />
namespace LanghuaNew.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Country33 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Country33));
        
        string IMigrationMetadata.Id
        {
            get { return "201607180135454_Country33"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
